### PR TITLE
Send Webhooks only to apps that have been created.

### PR DESCRIPTION
**Pull request by yurikoval**
- Limit webhook sending to `created` review apps.
- Add a log where the webhook is being sent to.

### CODE REVIEW

**Comment by yurikoval** [comment]
@jcarbaugh

**Comment by jcarbaugh** [comment]
@yurikoval thanks for the tag! I wasn't getting notifications for new PRs, but will take a look at this today.

**Comment by jcarbaugh** [comment]
@yurikoval it looks like all tests fail with this change and it would be good to have the tests be aware of the new created filter. I'd be happy to have you contribute some tests on this PR or I can merge into a branch and add the tests myself. Let me know!

**Comment by yurikoval** [comment]
@jcarbaugh I don't have access to the branch anymore to make any changes, so feel free to take over. I am going to close this PR.

**Pull request closed without merging**
